name: aggregator-cli-CI

pool:
  vmImage: vs2017-win2016

trigger:
  batch: true
  paths:
    include:
    - src/*

pr:
  paths:
    include:
    - src/*

steps:
- task: DeleteFiles@1
  displayName: 'Delete Directory.Build.targets from src/aggregator-function'
  inputs:
    SourceFolder: 'src/aggregator-function'
    Contents: Directory.Build.targets

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: 'src/aggregator-cli.sln'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: 'src/aggregator-cli.sln'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test (Unit)'
  inputs:
    command: test
    projects: 'src/**/*unittest*.csproj'

- task: DownloadSecureFile@1
  displayName: 'Get test configuration data'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  inputs:
    secureFile: logon-data.json

- task: DotNetCoreCLI@2
  displayName: 'dotnet test (Integration)'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: test
    projects: 'src/**/*integrationtest*.csproj'
